---
title: "energy"
author: "Tahmid Hossain Bhuiyan"
date: "2026-02-10"
output: html_document
---

## Renewable Energy Dataset
``` {r}
library(readr)
energy <- read_csv('../../data/IRENA data.csv', skip=1)
```

## Gapminder Datase
``` {r}
library(gapminder)
library(dplyr)

data(gapminder)
gapminder %>% head
```

## Carbon emission dataset
```{r}
library(dplyr)
library(readr)


url <- 'https://nyc3.digitaloceanspaces.com/owid-public/data/co2/owid-co2-data.csv'

carbon <-
  read_csv(url)
carbon %>% head
```

## Levelized Cost of Energy

```{r}
library(readr)
library(dplyr)
url <- 'https://raw.githubusercontent.com/ericmkeen/sewanee_esus/master/02_energy_sector/levelized-cost-of-energy.csv'
econ <- read_csv(url)
econ %>% head
```

```{r}
library(ggplot2)
ggplot(econ,
       aes(x=year,
           y=cost,
           color=source))+
  geom_point()+
  geom_hline(yintercept=0.05)+
  geom_hline(yintercept=0.18,lty=3)+
  annotate(geom='text',
           x=1990,y=0.1,
           size=3,
           label='Range of fossil fuel 
           costs')
```


```{r}
library(knitr)
econ %>% filter(year==2020) %>% 
  group_by(source) %>% 
  summarize(cost= mean(cost,na.rm=TRUE)) %>% 
  kable
```


